import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { QUADRANTS, RINGS, type Quadrant, type Ring, type Technology } from "./types.js";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const DATA_PATH = path.join(__dirname, "..", "sdtr.json");

function normalizeRing(raw: string): Ring {
  const match = RINGS.find((ring) => ring === raw.toUpperCase());
  if (!match) {
    console.error(`Warning: unknown ring value "${raw}" in sdtr.json, leaving as-is`);
    return raw.toUpperCase() as Ring;
  }
  return match;
}

function normalizeQuadrant(raw: string): Quadrant {
  const match = QUADRANTS.find((quadrant) => quadrant.toLowerCase() === raw.toLowerCase());
  if (!match) {
    console.error(`Warning: unknown quadrant value "${raw}" in sdtr.json, leaving as-is`);
    return raw as Quadrant;
  }
  return match;
}

let cache: Technology[] | undefined;

/**
 * Load and normalize sdtr.json. Cached after first read since the file is
 * only regenerated by the toml -> json conversion script, not at runtime.
 */
export function loadTechnologies(): Technology[] {
  if (cache) {
    return cache;
  }

  let raw: unknown;
  try {
    raw = JSON.parse(fs.readFileSync(DATA_PATH, "utf8"));
  } catch (error) {
    throw new Error(
      `Could not read tech radar data at ${DATA_PATH}. ` +
        `Run "npm run conv" in the project root to generate it. ` +
        `Underlying error: ${error instanceof Error ? error.message : String(error)}`
    );
  }

  if (!Array.isArray(raw)) {
    throw new Error(`Expected ${DATA_PATH} to contain a JSON array of technologies`);
  }

  cache = (raw as Record<string, unknown>[]).map((entry) => ({
    ...(entry as unknown as Technology),
    ring: normalizeRing(String(entry.ring)),
    quadrant: normalizeQuadrant(String(entry.quadrant))
  }));

  return cache;
}

/**
 * Find technologies matching a name query against label or title.
 * Returns exact (case-insensitive) matches first; falls back to
 * substring matches when there is no exact match.
 */
export function findTechnologies(name: string): Technology[] {
  const technologies = loadTechnologies();
  const query = name.trim().toLowerCase();

  const exact = technologies.filter(
    (tech) => tech.label.toLowerCase() === query || tech.title.toLowerCase() === query
  );
  if (exact.length > 0) {
    return exact;
  }

  return technologies.filter(
    (tech) => tech.label.toLowerCase().includes(query) || tech.title.toLowerCase().includes(query)
  );
}

export interface ListFilter {
  ring?: Ring;
  quadrant?: Quadrant;
}

export function listTechnologies(filter: ListFilter): Technology[] {
  const technologies = loadTechnologies();
  return technologies.filter((tech) => {
    if (filter.ring && tech.ring !== filter.ring) {
      return false;
    }
    if (filter.quadrant && tech.quadrant !== filter.quadrant) {
      return false;
    }
    return true;
  });
}
